### ISSUE TITLE
Bro, why does the KL loss never decrease?

### ISSUE THREAD

**Issue by kevinbro96** [viniciusguigo/pytorch_dvib#3]
I runned dvib.py and the KL loss seems never decrease.

**Comment by viniciusguigo** [comment]
That's a good point. Need to double-check how the KL loss is computed between the encoder distribution and the prior (this line: https://github.com/viniciusguigo/pytorch_dvib/blob/master/dvib.py#L120). Have you tried anything else?

**Comment by viniciusguigo** [comment]
I'm closing this issue because it has been inactive for a few weeks. Please re-open it if necessary. Thanks!
